import './globals.css'
import type { Metadata } from 'next'
import { Sen } from 'next/font/google'
import 'remixicon/fonts/remixicon.css'

const sen = Sen({ weight: ["400", "500", "700"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Raimuna Subang 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='./icons/logo-brand.png'/>
      </head>
      <body className={sen.className}>{children}</body>
    </html>
  )
}
